# Generated by Django 4.2.3 on 2023-12-22 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicchatroom',
            name='users',
            field=models.ManyToManyField(help_text='Users who are connected to the chat', to=settings.AUTH_USER_MODEL),
        ),
    ]
